/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("Employees1ObjectPageObjectPage journey");

        opaTest("Navigate to Employees1ObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheEmployees1ListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheEmployees1ListGenerated.onTable().iCheckRows();
            When.onTheEmployees1ListGenerated.onTable().iPressRow(0);

            Then.onTheEmployees1ObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the number of sections of the Object Page", function (_Given, _When, Then) {
            Then.onTheEmployees1ObjectPageGenerated.iCheckNumberOfSections(4);
        });

        opaTest("Check the FieldGroup::EmployeeInfo section of the Object Page", function (_Given, When, Then) {
            When.onTheEmployees1ObjectPageGenerated.iGoToSection({ section: "FieldGroup::EmployeeInfo" });
            Then.onTheEmployees1ObjectPageGenerated.iCheckSection({ section: "FieldGroup::EmployeeInfo" });
            Then.onTheEmployees1ObjectPageGenerated.onForm({ section: "FieldGroup::EmployeeInfo" }).iCheckField({ property: "employeeId" });
            Then.onTheEmployees1ObjectPageGenerated.onForm({ section: "FieldGroup::EmployeeInfo" }).iCheckField({ property: "name" });
            Then.onTheEmployees1ObjectPageGenerated.onForm({ section: "FieldGroup::EmployeeInfo" }).iCheckField({ property: "email" });
            Then.onTheEmployees1ObjectPageGenerated.onForm({ section: "FieldGroup::EmployeeInfo" }).iCheckField({ property: "department" });
            Then.onTheEmployees1ObjectPageGenerated.onForm({ section: "FieldGroup::EmployeeInfo" }).iCheckField({ property: "designation" });
            Then.onTheEmployees1ObjectPageGenerated.onForm({ section: "FieldGroup::EmployeeInfo" }).iCheckField({ property: "salary" });
            Then.onTheEmployees1ObjectPageGenerated.onForm({ section: "FieldGroup::EmployeeInfo" }).iCheckField({ property: "status" });
        });

        opaTest("Check the project::FieldGroup::ProjectDetails section of the Object Page", function (_Given, When, Then) {
            When.onTheEmployees1ObjectPageGenerated.iGoToSection({ section: "project::FieldGroup::ProjectDetails" });
            Then.onTheEmployees1ObjectPageGenerated.iCheckSection({ section: "project::FieldGroup::ProjectDetails" });
            Then.onTheEmployees1ObjectPageGenerated.onForm({ section: "project::FieldGroup::ProjectDetails" }).iCheckField({ property: "PTitle" });
            Then.onTheEmployees1ObjectPageGenerated.onForm({ section: "project::FieldGroup::ProjectDetails" }).iCheckField({ property: "PDescription" });
            Then.onTheEmployees1ObjectPageGenerated.onForm({ section: "project::FieldGroup::ProjectDetails" }).iCheckField({ property: "PType" });
            Then.onTheEmployees1ObjectPageGenerated.onForm({ section: "project::FieldGroup::ProjectDetails" }).iCheckField({ property: "PStartedDate" });
            Then.onTheEmployees1ObjectPageGenerated.onForm({ section: "project::FieldGroup::ProjectDetails" }).iCheckField({ property: "PEndDate" });
            Then.onTheEmployees1ObjectPageGenerated.onForm({ section: "project::FieldGroup::ProjectDetails" }).iCheckField({ property: "TeamSize" });
        });

        opaTest("Check the skillset::LineItem section of the Object Page", function (_Given, When, Then) {
            When.onTheEmployees1ObjectPageGenerated.iGoToSection({ section: "skillset::LineItem" });
            Then.onTheEmployees1ObjectPageGenerated.iCheckSection({ section: "skillset::LineItem" });
        });

        opaTest("Check the wexp::LineItem section of the Object Page", function (_Given, When, Then) {
            When.onTheEmployees1ObjectPageGenerated.iGoToSection({ section: "wexp::LineItem" });
            Then.onTheEmployees1ObjectPageGenerated.iCheckSection({ section: "wexp::LineItem" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});